import React from 'react';
import type { ReactNode } from 'react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  Book,
  BookOpen,
  Box,
  Braces,
  Check,
  ChevronRight,
  Circle,
  Cloud,
  Code,
  Cog,
  Command,
  Copy,
  Database,
  Download,
  ExternalLink,
  Eye,
  File,
  FileCode,
  FileText,
  Folder,
  FolderOpen,
  Gauge,
  Github,
  Globe,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  Key,
  Laptop,
  Layers,
  Layout,
  Library,
  Lightbulb,
  Link,
  List,
  Lock,
  Mail,
  Map,
  MessageSquare,
  Monitor,
  Moon,
  Package,
  Paintbrush,
  Palette,
  Pencil,
  Play,
  Plug,
  Plus,
  Puzzle,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Trash,
  Upload,
  User,
  Wand2,
  Wrench,
  Zap
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<{ size?: number }>> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  book: Book,
  'book-open': BookOpen,
  box: Box,
  braces: Braces,
  check: Check,
  'chevron-right': ChevronRight,
  circle: Circle,
  cloud: Cloud,
  code: Code,
  cog: Cog,
  command: Command,
  copy: Copy,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  file: File,
  'file-code': FileCode,
  'file-text': FileText,
  folder: Folder,
  'folder-open': FolderOpen,
  gauge: Gauge,
  github: Github,
  globe: Globe,
  hash: Hash,
  heart: Heart,
  'help-circle': HelpCircle,
  home: Home,
  image: Image,
  info: Info,
  key: Key,
  laptop: Laptop,
  layers: Layers,
  layout: Layout,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  lock: Lock,
  mail: Mail,
  map: Map,
  'message-square': MessageSquare,
  monitor: Monitor,
  moon: Moon,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  puzzle: Puzzle,
  rocket: Rocket,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  terminal: Terminal,
  trash: Trash,
  upload: Upload,
  user: User,
  wand: Wand2,
  wrench: Wrench,
  zap: Zap
};

export function resolveIcon(name: string, size = 18): ReactNode {
  const Component = iconMap[name];
  if (!Component) return null;
  return <Component size={size} />;
}

export function Icon({
  name,
  size = 18,
  color
}: {
  name: string;
  size?: number;
  color?: string;
}) {
  const Component = iconMap[name];
  if (!Component) return null;

  const style = color ? { color } : undefined;
  return (
    <span className="void-icon" style={style}>
      <Component size={size} />
    </span>
  );
}
